### ISSUE TITLE
can't deploy `controller.jsonnet`

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/sealed-secrets#9]
So, I tried jsonnet to generate json from `controller.jsonnet`. Then `kubectl create -f` has error

```
$ jsonnet controller.jsonnet > controller.json
$ kubectl create -f controller.json 
error: unable to decode "controller.json": Object 'Kind' is missing in
``` 

cc/ @anguslees

**Comment by anguslees** [comment]
You need to use `jsonnet --multi` or `kubecfg`.  The file contains multiple
json objects.

- Gus

**Comment by ngtuna** [comment]
`jsonnet --multi` gave me this error:
```
$ jsonnet --multi kubeless.jsonnet 
ERROR: Must give filename
```
And I tried `kubecfg` with no luck :-( 
https://github.com/ksonnet/kubecfg/issues/25

**Comment by Nikkau** [comment]
The `--multi` take a path, you should try `jsonnet --multi . controller.jsonnet`.

**Comment by ngtuna** [comment]
Gotcha. Thanks @Nikkau 👍 Close it now.
